name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Python 3.6, python: 3.6, os: ubuntu}
          - {name: Python 3.7, python: 3.7, os: ubuntu}
          - {name: Python 3.8, python: 3.8, os: ubuntu}
          - {name: Python 3.9, python: 3.9, os: ubuntu}
          - {name: Python 3.10, python: "3.10", os: ubuntu}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools tox codecov
      - name: Test
        run: |
          tox -e py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
